[profile.default]
optimizer_runs = 44444444
via_ir = true
ffi = true
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
evm_version = "paris"

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz = 10

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
